# Generated by Django 4.1.7 on 2024-05-24 12:10

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234XXXXXXXXXX' or '0XXXXXXXXXX'.", regex='^\\+234\\d{10}$|^0\\d{10}$')])),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('accomodation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('are_you_coming_only', models.CharField(choices=[('I am coming alone', 'I am coming alone'), ('I am coming with children', 'I am coming with children')], max_length=255)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50)),
                ('age_group', models.CharField(choices=[('I am coming alone', 'I am coming alone'), ('I am coming with children', 'I am coming with children')], max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
