# Generated by Django 4.1.7 on 2024-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='are_you_coming_only',
        ),
        migrations.AddField(
            model_name='person',
            name='are_you_coming_alone',
            field=models.CharField(choices=[('I am coming alone', 'I am coming alone'), ('I am coming with children', 'I am coming with children')], default=1, max_length=255, verbose_name='Are you coming alone?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='age_group',
            field=models.CharField(choices=[('0 - 18', '0 - 18'), ('19 - 25', '19 - 25'), ('26 - 30', '26 - 30'), ('31 - 40', '31 - 40'), ('41 - 50', '41 - 50'), ('51 - 60', '51 - 60')], max_length=50),
        ),
    ]
