# Generated by Django 4.1.7 on 2024-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_person_are_you_coming_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has been used already'}, max_length=254, unique=True),
        ),
    ]
